/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BrickConfigsChangeDetail, BrickDropDetail, BrickPathDetail, BrickRulesChangeDetail, BrickStylesChangeDetail, BrickValidationsChangeDetail, DataChangeDetail, SpecChangeDetail } from "./utils/events";
import { BrickMold, BrickSpec, UploadedFile, Utils, ValidationResult } from "@streamline-pulse/formkrafter-core";
export { BrickConfigsChangeDetail, BrickDropDetail, BrickPathDetail, BrickRulesChangeDetail, BrickStylesChangeDetail, BrickValidationsChangeDetail, DataChangeDetail, SpecChangeDetail } from "./utils/events";
export { BrickMold, BrickSpec, UploadedFile, Utils, ValidationResult } from "@streamline-pulse/formkrafter-core";
export namespace Components {
    interface FkBrickActions {
        "path": string;
        /**
          * @default false
         */
        "selected": boolean;
    }
    interface FkBrickList {
    }
    interface FkBrickMoldItem {
        "brickMold": BrickMold;
    }
    interface FkBrickNotFound {
    }
    interface FkBrickRender {
        "brickSpec": BrickSpec;
        "data"?: Record<string, unknown>;
        "dataMap"?: Record<string, unknown>;
        /**
          * @default false
         */
        "editable": boolean;
        /**
          * @default {}
         */
        "errors": Record<string, string>;
        "locale"?: string;
        /**
          * @default '0'
         */
        "path": string;
        "rootSpec"?: BrickSpec;
        "selectedUid"?: string;
        "utils": Utils;
    }
    interface FkCodeEditor {
        /**
          * @default []
         */
        "completions": string[];
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface FkDataGrid {
        /**
          * @default false
         */
        "disabled": boolean;
        "locale"?: string;
        "spec": BrickSpec;
        "utils": Utils;
        "validateRows": () => Promise<ValidationResult>;
        "value"?: unknown;
    }
    interface FkDropArea {
        /**
          * @default false
         */
        "empty": boolean;
        "path": string;
    }
    interface FkEmptyForm {
    }
    interface FkFileInput {
        "accept"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "multiple": boolean;
        "uploadUrl"?: string;
        "value"?: UploadedFile | UploadedFile[];
    }
    interface FkFormBuilder {
        "data"?: Record<string, unknown>;
        /**
          * @default []
         */
        "locales": string[];
        "spec"?: BrickSpec;
    }
    interface FkFormRender {
        "data"?: Record<string, unknown>;
        /**
          * @default false
         */
        "editable": boolean;
        "locale"?: string;
        "selectedUid"?: string;
        "spec": BrickSpec;
        "validate": () => Promise<ValidationResult>;
    }
    interface FkPropertyPanel {
        "brick": BrickSpec;
        "editLocale"?: string;
        /**
          * @default []
         */
        "fields": string[];
        /**
          * @default []
         */
        "locales": string[];
    }
    interface FkRulesEditor {
        "brick": BrickSpec;
        /**
          * @default []
         */
        "fields": string[];
    }
    interface FkSelectInput {
        "configs"?: Record<string, unknown>;
        "dataMap"?: Record<string, unknown>;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "invalid": boolean;
        /**
          * @default false
         */
        "multiple": boolean;
        "value"?: string | string[];
    }
    interface FkSignatureInput {
        /**
          * @default false
         */
        "disabled": boolean;
        "value"?: string;
    }
    interface FkStepper {
        "dataMap"?: Record<string, unknown>;
        /**
          * @default false
         */
        "editable": boolean;
        "locale"?: string;
        "spec"?: BrickSpec;
        /**
          * @default []
         */
        "stepLabels": string[];
    }
    interface FkTabs {
        "dataMap"?: Record<string, unknown>;
        /**
          * @default false
         */
        "editable": boolean;
        "locale"?: string;
        "spec"?: BrickSpec;
        /**
          * @default []
         */
        "tabLabels": string[];
    }
}
export interface FkBrickActionsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFkBrickActionsElement;
}
export interface FkBrickRenderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFkBrickRenderElement;
}
export interface FkCodeEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFkCodeEditorElement;
}
export interface FkDataGridCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFkDataGridElement;
}
export interface FkDropAreaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFkDropAreaElement;
}
export interface FkFileInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFkFileInputElement;
}
export interface FkFormBuilderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFkFormBuilderElement;
}
export interface FkFormRenderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFkFormRenderElement;
}
export interface FkPropertyPanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFkPropertyPanelElement;
}
export interface FkRulesEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFkRulesEditorElement;
}
export interface FkSelectInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFkSelectInputElement;
}
export interface FkSignatureInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFkSignatureInputElement;
}
export interface FkStepperCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFkStepperElement;
}
export interface FkTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFkTabsElement;
}
declare global {
    interface HTMLFkBrickActionsElementEventMap {
        "brickRemove": BrickPathDetail;
        "brickDuplicate": BrickPathDetail;
        "brickDrop": BrickDropDetail;
        "brickSelect": BrickPathDetail;
    }
    interface HTMLFkBrickActionsElement extends Components.FkBrickActions, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFkBrickActionsElementEventMap>(type: K, listener: (this: HTMLFkBrickActionsElement, ev: FkBrickActionsCustomEvent<HTMLFkBrickActionsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFkBrickActionsElementEventMap>(type: K, listener: (this: HTMLFkBrickActionsElement, ev: FkBrickActionsCustomEvent<HTMLFkBrickActionsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFkBrickActionsElement: {
        prototype: HTMLFkBrickActionsElement;
        new (): HTMLFkBrickActionsElement;
    };
    interface HTMLFkBrickListElement extends Components.FkBrickList, HTMLStencilElement {
    }
    var HTMLFkBrickListElement: {
        prototype: HTMLFkBrickListElement;
        new (): HTMLFkBrickListElement;
    };
    interface HTMLFkBrickMoldItemElement extends Components.FkBrickMoldItem, HTMLStencilElement {
    }
    var HTMLFkBrickMoldItemElement: {
        prototype: HTMLFkBrickMoldItemElement;
        new (): HTMLFkBrickMoldItemElement;
    };
    interface HTMLFkBrickNotFoundElement extends Components.FkBrickNotFound, HTMLStencilElement {
    }
    var HTMLFkBrickNotFoundElement: {
        prototype: HTMLFkBrickNotFoundElement;
        new (): HTMLFkBrickNotFoundElement;
    };
    interface HTMLFkBrickRenderElementEventMap {
        "brickDataChange": Record<string, unknown>;
        "brickConfigsChange": BrickConfigsChangeDetail;
        "brickStylesChange": BrickStylesChangeDetail;
        "brickValidationsChange": BrickValidationsChangeDetail;
        "brickRulesChange": BrickRulesChangeDetail;
        "brickRemove": BrickPathDetail;
        "brickDuplicate": BrickPathDetail;
    }
    interface HTMLFkBrickRenderElement extends Components.FkBrickRender, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFkBrickRenderElementEventMap>(type: K, listener: (this: HTMLFkBrickRenderElement, ev: FkBrickRenderCustomEvent<HTMLFkBrickRenderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFkBrickRenderElementEventMap>(type: K, listener: (this: HTMLFkBrickRenderElement, ev: FkBrickRenderCustomEvent<HTMLFkBrickRenderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFkBrickRenderElement: {
        prototype: HTMLFkBrickRenderElement;
        new (): HTMLFkBrickRenderElement;
    };
    interface HTMLFkCodeEditorElementEventMap {
        "codeChange": string;
    }
    interface HTMLFkCodeEditorElement extends Components.FkCodeEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFkCodeEditorElementEventMap>(type: K, listener: (this: HTMLFkCodeEditorElement, ev: FkCodeEditorCustomEvent<HTMLFkCodeEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFkCodeEditorElementEventMap>(type: K, listener: (this: HTMLFkCodeEditorElement, ev: FkCodeEditorCustomEvent<HTMLFkCodeEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFkCodeEditorElement: {
        prototype: HTMLFkCodeEditorElement;
        new (): HTMLFkCodeEditorElement;
    };
    interface HTMLFkDataGridElementEventMap {
        "gridValueChange": Array<Record<string, unknown>> | undefined;
    }
    interface HTMLFkDataGridElement extends Components.FkDataGrid, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFkDataGridElementEventMap>(type: K, listener: (this: HTMLFkDataGridElement, ev: FkDataGridCustomEvent<HTMLFkDataGridElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFkDataGridElementEventMap>(type: K, listener: (this: HTMLFkDataGridElement, ev: FkDataGridCustomEvent<HTMLFkDataGridElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFkDataGridElement: {
        prototype: HTMLFkDataGridElement;
        new (): HTMLFkDataGridElement;
    };
    interface HTMLFkDropAreaElementEventMap {
        "brickDrop": BrickDropDetail;
    }
    interface HTMLFkDropAreaElement extends Components.FkDropArea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFkDropAreaElementEventMap>(type: K, listener: (this: HTMLFkDropAreaElement, ev: FkDropAreaCustomEvent<HTMLFkDropAreaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFkDropAreaElementEventMap>(type: K, listener: (this: HTMLFkDropAreaElement, ev: FkDropAreaCustomEvent<HTMLFkDropAreaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFkDropAreaElement: {
        prototype: HTMLFkDropAreaElement;
        new (): HTMLFkDropAreaElement;
    };
    interface HTMLFkEmptyFormElement extends Components.FkEmptyForm, HTMLStencilElement {
    }
    var HTMLFkEmptyFormElement: {
        prototype: HTMLFkEmptyFormElement;
        new (): HTMLFkEmptyFormElement;
    };
    interface HTMLFkFileInputElementEventMap {
        "fileValueChange": UploadedFile | UploadedFile[] | undefined;
    }
    interface HTMLFkFileInputElement extends Components.FkFileInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFkFileInputElementEventMap>(type: K, listener: (this: HTMLFkFileInputElement, ev: FkFileInputCustomEvent<HTMLFkFileInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFkFileInputElementEventMap>(type: K, listener: (this: HTMLFkFileInputElement, ev: FkFileInputCustomEvent<HTMLFkFileInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFkFileInputElement: {
        prototype: HTMLFkFileInputElement;
        new (): HTMLFkFileInputElement;
    };
    interface HTMLFkFormBuilderElementEventMap {
        "specChange": SpecChangeDetail;
    }
    interface HTMLFkFormBuilderElement extends Components.FkFormBuilder, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFkFormBuilderElementEventMap>(type: K, listener: (this: HTMLFkFormBuilderElement, ev: FkFormBuilderCustomEvent<HTMLFkFormBuilderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFkFormBuilderElementEventMap>(type: K, listener: (this: HTMLFkFormBuilderElement, ev: FkFormBuilderCustomEvent<HTMLFkFormBuilderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFkFormBuilderElement: {
        prototype: HTMLFkFormBuilderElement;
        new (): HTMLFkFormBuilderElement;
    };
    interface HTMLFkFormRenderElementEventMap {
        "formDataChange": DataChangeDetail;
        "formSubmit": DataChangeDetail;
    }
    interface HTMLFkFormRenderElement extends Components.FkFormRender, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFkFormRenderElementEventMap>(type: K, listener: (this: HTMLFkFormRenderElement, ev: FkFormRenderCustomEvent<HTMLFkFormRenderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFkFormRenderElementEventMap>(type: K, listener: (this: HTMLFkFormRenderElement, ev: FkFormRenderCustomEvent<HTMLFkFormRenderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFkFormRenderElement: {
        prototype: HTMLFkFormRenderElement;
        new (): HTMLFkFormRenderElement;
    };
    interface HTMLFkPropertyPanelElementEventMap {
        "brickConfigsChange": BrickConfigsChangeDetail;
        "brickValidationsChange": BrickValidationsChangeDetail;
        "brickStylesChange": BrickStylesChangeDetail;
    }
    interface HTMLFkPropertyPanelElement extends Components.FkPropertyPanel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFkPropertyPanelElementEventMap>(type: K, listener: (this: HTMLFkPropertyPanelElement, ev: FkPropertyPanelCustomEvent<HTMLFkPropertyPanelElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFkPropertyPanelElementEventMap>(type: K, listener: (this: HTMLFkPropertyPanelElement, ev: FkPropertyPanelCustomEvent<HTMLFkPropertyPanelElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFkPropertyPanelElement: {
        prototype: HTMLFkPropertyPanelElement;
        new (): HTMLFkPropertyPanelElement;
    };
    interface HTMLFkRulesEditorElementEventMap {
        "brickRulesChange": BrickRulesChangeDetail;
    }
    interface HTMLFkRulesEditorElement extends Components.FkRulesEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFkRulesEditorElementEventMap>(type: K, listener: (this: HTMLFkRulesEditorElement, ev: FkRulesEditorCustomEvent<HTMLFkRulesEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFkRulesEditorElementEventMap>(type: K, listener: (this: HTMLFkRulesEditorElement, ev: FkRulesEditorCustomEvent<HTMLFkRulesEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFkRulesEditorElement: {
        prototype: HTMLFkRulesEditorElement;
        new (): HTMLFkRulesEditorElement;
    };
    interface HTMLFkSelectInputElementEventMap {
        "selectValueChange": string | string[] | undefined;
    }
    interface HTMLFkSelectInputElement extends Components.FkSelectInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFkSelectInputElementEventMap>(type: K, listener: (this: HTMLFkSelectInputElement, ev: FkSelectInputCustomEvent<HTMLFkSelectInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFkSelectInputElementEventMap>(type: K, listener: (this: HTMLFkSelectInputElement, ev: FkSelectInputCustomEvent<HTMLFkSelectInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFkSelectInputElement: {
        prototype: HTMLFkSelectInputElement;
        new (): HTMLFkSelectInputElement;
    };
    interface HTMLFkSignatureInputElementEventMap {
        "signatureChange": string | undefined;
    }
    interface HTMLFkSignatureInputElement extends Components.FkSignatureInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFkSignatureInputElementEventMap>(type: K, listener: (this: HTMLFkSignatureInputElement, ev: FkSignatureInputCustomEvent<HTMLFkSignatureInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFkSignatureInputElementEventMap>(type: K, listener: (this: HTMLFkSignatureInputElement, ev: FkSignatureInputCustomEvent<HTMLFkSignatureInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFkSignatureInputElement: {
        prototype: HTMLFkSignatureInputElement;
        new (): HTMLFkSignatureInputElement;
    };
    interface HTMLFkStepperElementEventMap {
        "stepTouch": { keys: string[] };
        "stepperSubmit": void;
    }
    interface HTMLFkStepperElement extends Components.FkStepper, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFkStepperElementEventMap>(type: K, listener: (this: HTMLFkStepperElement, ev: FkStepperCustomEvent<HTMLFkStepperElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFkStepperElementEventMap>(type: K, listener: (this: HTMLFkStepperElement, ev: FkStepperCustomEvent<HTMLFkStepperElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFkStepperElement: {
        prototype: HTMLFkStepperElement;
        new (): HTMLFkStepperElement;
    };
    interface HTMLFkTabsElementEventMap {
        "stepTouch": { keys: string[] };
    }
    interface HTMLFkTabsElement extends Components.FkTabs, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFkTabsElementEventMap>(type: K, listener: (this: HTMLFkTabsElement, ev: FkTabsCustomEvent<HTMLFkTabsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFkTabsElementEventMap>(type: K, listener: (this: HTMLFkTabsElement, ev: FkTabsCustomEvent<HTMLFkTabsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFkTabsElement: {
        prototype: HTMLFkTabsElement;
        new (): HTMLFkTabsElement;
    };
    interface HTMLElementTagNameMap {
        "fk-brick-actions": HTMLFkBrickActionsElement;
        "fk-brick-list": HTMLFkBrickListElement;
        "fk-brick-mold-item": HTMLFkBrickMoldItemElement;
        "fk-brick-not-found": HTMLFkBrickNotFoundElement;
        "fk-brick-render": HTMLFkBrickRenderElement;
        "fk-code-editor": HTMLFkCodeEditorElement;
        "fk-data-grid": HTMLFkDataGridElement;
        "fk-drop-area": HTMLFkDropAreaElement;
        "fk-empty-form": HTMLFkEmptyFormElement;
        "fk-file-input": HTMLFkFileInputElement;
        "fk-form-builder": HTMLFkFormBuilderElement;
        "fk-form-render": HTMLFkFormRenderElement;
        "fk-property-panel": HTMLFkPropertyPanelElement;
        "fk-rules-editor": HTMLFkRulesEditorElement;
        "fk-select-input": HTMLFkSelectInputElement;
        "fk-signature-input": HTMLFkSignatureInputElement;
        "fk-stepper": HTMLFkStepperElement;
        "fk-tabs": HTMLFkTabsElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface FkBrickActions {
        "onBrickDrop"?: (event: FkBrickActionsCustomEvent<BrickDropDetail>) => void;
        "onBrickDuplicate"?: (event: FkBrickActionsCustomEvent<BrickPathDetail>) => void;
        "onBrickRemove"?: (event: FkBrickActionsCustomEvent<BrickPathDetail>) => void;
        "onBrickSelect"?: (event: FkBrickActionsCustomEvent<BrickPathDetail>) => void;
        "path": string;
        /**
          * @default false
         */
        "selected"?: boolean;
    }
    interface FkBrickList {
    }
    interface FkBrickMoldItem {
        "brickMold": BrickMold;
    }
    interface FkBrickNotFound {
    }
    interface FkBrickRender {
        "brickSpec": BrickSpec;
        "data"?: Record<string, unknown>;
        "dataMap"?: Record<string, unknown>;
        /**
          * @default false
         */
        "editable"?: boolean;
        /**
          * @default {}
         */
        "errors"?: Record<string, string>;
        "locale"?: string;
        "onBrickConfigsChange"?: (event: FkBrickRenderCustomEvent<BrickConfigsChangeDetail>) => void;
        "onBrickDataChange"?: (event: FkBrickRenderCustomEvent<Record<string, unknown>>) => void;
        "onBrickDuplicate"?: (event: FkBrickRenderCustomEvent<BrickPathDetail>) => void;
        "onBrickRemove"?: (event: FkBrickRenderCustomEvent<BrickPathDetail>) => void;
        "onBrickRulesChange"?: (event: FkBrickRenderCustomEvent<BrickRulesChangeDetail>) => void;
        "onBrickStylesChange"?: (event: FkBrickRenderCustomEvent<BrickStylesChangeDetail>) => void;
        "onBrickValidationsChange"?: (event: FkBrickRenderCustomEvent<BrickValidationsChangeDetail>) => void;
        /**
          * @default '0'
         */
        "path"?: string;
        "rootSpec"?: BrickSpec;
        "selectedUid"?: string;
        "utils": Utils;
    }
    interface FkCodeEditor {
        /**
          * @default []
         */
        "completions"?: string[];
        "onCodeChange"?: (event: FkCodeEditorCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface FkDataGrid {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "locale"?: string;
        "onGridValueChange"?: (event: FkDataGridCustomEvent<Array<Record<string, unknown>> | undefined>) => void;
        "spec": BrickSpec;
        "utils": Utils;
        "value"?: unknown;
    }
    interface FkDropArea {
        /**
          * @default false
         */
        "empty"?: boolean;
        "onBrickDrop"?: (event: FkDropAreaCustomEvent<BrickDropDetail>) => void;
        "path": string;
    }
    interface FkEmptyForm {
    }
    interface FkFileInput {
        "accept"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "multiple"?: boolean;
        "onFileValueChange"?: (event: FkFileInputCustomEvent<UploadedFile | UploadedFile[] | undefined>) => void;
        "uploadUrl"?: string;
        "value"?: UploadedFile | UploadedFile[];
    }
    interface FkFormBuilder {
        "data"?: Record<string, unknown>;
        /**
          * @default []
         */
        "locales"?: string[];
        "onSpecChange"?: (event: FkFormBuilderCustomEvent<SpecChangeDetail>) => void;
        "spec"?: BrickSpec;
    }
    interface FkFormRender {
        "data"?: Record<string, unknown>;
        /**
          * @default false
         */
        "editable"?: boolean;
        "locale"?: string;
        "onFormDataChange"?: (event: FkFormRenderCustomEvent<DataChangeDetail>) => void;
        "onFormSubmit"?: (event: FkFormRenderCustomEvent<DataChangeDetail>) => void;
        "selectedUid"?: string;
        "spec": BrickSpec;
    }
    interface FkPropertyPanel {
        "brick": BrickSpec;
        "editLocale"?: string;
        /**
          * @default []
         */
        "fields"?: string[];
        /**
          * @default []
         */
        "locales"?: string[];
        "onBrickConfigsChange"?: (event: FkPropertyPanelCustomEvent<BrickConfigsChangeDetail>) => void;
        "onBrickStylesChange"?: (event: FkPropertyPanelCustomEvent<BrickStylesChangeDetail>) => void;
        "onBrickValidationsChange"?: (event: FkPropertyPanelCustomEvent<BrickValidationsChangeDetail>) => void;
    }
    interface FkRulesEditor {
        "brick": BrickSpec;
        /**
          * @default []
         */
        "fields"?: string[];
        "onBrickRulesChange"?: (event: FkRulesEditorCustomEvent<BrickRulesChangeDetail>) => void;
    }
    interface FkSelectInput {
        "configs"?: Record<string, unknown>;
        "dataMap"?: Record<string, unknown>;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "invalid"?: boolean;
        /**
          * @default false
         */
        "multiple"?: boolean;
        "onSelectValueChange"?: (event: FkSelectInputCustomEvent<string | string[] | undefined>) => void;
        "value"?: string | string[];
    }
    interface FkSignatureInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onSignatureChange"?: (event: FkSignatureInputCustomEvent<string | undefined>) => void;
        "value"?: string;
    }
    interface FkStepper {
        "dataMap"?: Record<string, unknown>;
        /**
          * @default false
         */
        "editable"?: boolean;
        "locale"?: string;
        "onStepTouch"?: (event: FkStepperCustomEvent<{ keys: string[] }>) => void;
        "onStepperSubmit"?: (event: FkStepperCustomEvent<void>) => void;
        "spec"?: BrickSpec;
        /**
          * @default []
         */
        "stepLabels"?: string[];
    }
    interface FkTabs {
        "dataMap"?: Record<string, unknown>;
        /**
          * @default false
         */
        "editable"?: boolean;
        "locale"?: string;
        "onStepTouch"?: (event: FkTabsCustomEvent<{ keys: string[] }>) => void;
        "spec"?: BrickSpec;
        /**
          * @default []
         */
        "tabLabels"?: string[];
    }

    interface FkBrickActionsAttributes {
        "path": string;
        "selected": boolean;
    }
    interface FkBrickRenderAttributes {
        "path": string;
        "editable": boolean;
        "selectedUid": string;
        "locale": string;
    }
    interface FkCodeEditorAttributes {
        "value": string;
        "placeholder": string;
    }
    interface FkDataGridAttributes {
        "disabled": boolean;
        "locale": string;
    }
    interface FkDropAreaAttributes {
        "path": string;
        "empty": boolean;
    }
    interface FkFileInputAttributes {
        "disabled": boolean;
        "accept": string;
        "uploadUrl": string;
        "multiple": boolean;
    }
    interface FkFormRenderAttributes {
        "editable": boolean;
        "selectedUid": string;
        "locale": string;
    }
    interface FkPropertyPanelAttributes {
        "editLocale": string;
    }
    interface FkSelectInputAttributes {
        "value": string | string[];
        "disabled": boolean;
        "multiple": boolean;
        "invalid": boolean;
    }
    interface FkSignatureInputAttributes {
        "value": string;
        "disabled": boolean;
    }
    interface FkStepperAttributes {
        "editable": boolean;
        "locale": string;
    }
    interface FkTabsAttributes {
        "editable": boolean;
        "locale": string;
    }

    interface IntrinsicElements {
        "fk-brick-actions": Omit<FkBrickActions, keyof FkBrickActionsAttributes> & { [K in keyof FkBrickActions & keyof FkBrickActionsAttributes]?: FkBrickActions[K] } & { [K in keyof FkBrickActions & keyof FkBrickActionsAttributes as `attr:${K}`]?: FkBrickActionsAttributes[K] } & { [K in keyof FkBrickActions & keyof FkBrickActionsAttributes as `prop:${K}`]?: FkBrickActions[K] } & OneOf<"path", FkBrickActions["path"], FkBrickActionsAttributes["path"]>;
        "fk-brick-list": FkBrickList;
        "fk-brick-mold-item": FkBrickMoldItem;
        "fk-brick-not-found": FkBrickNotFound;
        "fk-brick-render": Omit<FkBrickRender, keyof FkBrickRenderAttributes> & { [K in keyof FkBrickRender & keyof FkBrickRenderAttributes]?: FkBrickRender[K] } & { [K in keyof FkBrickRender & keyof FkBrickRenderAttributes as `attr:${K}`]?: FkBrickRenderAttributes[K] } & { [K in keyof FkBrickRender & keyof FkBrickRenderAttributes as `prop:${K}`]?: FkBrickRender[K] };
        "fk-code-editor": Omit<FkCodeEditor, keyof FkCodeEditorAttributes> & { [K in keyof FkCodeEditor & keyof FkCodeEditorAttributes]?: FkCodeEditor[K] } & { [K in keyof FkCodeEditor & keyof FkCodeEditorAttributes as `attr:${K}`]?: FkCodeEditorAttributes[K] } & { [K in keyof FkCodeEditor & keyof FkCodeEditorAttributes as `prop:${K}`]?: FkCodeEditor[K] };
        "fk-data-grid": Omit<FkDataGrid, keyof FkDataGridAttributes> & { [K in keyof FkDataGrid & keyof FkDataGridAttributes]?: FkDataGrid[K] } & { [K in keyof FkDataGrid & keyof FkDataGridAttributes as `attr:${K}`]?: FkDataGridAttributes[K] } & { [K in keyof FkDataGrid & keyof FkDataGridAttributes as `prop:${K}`]?: FkDataGrid[K] };
        "fk-drop-area": Omit<FkDropArea, keyof FkDropAreaAttributes> & { [K in keyof FkDropArea & keyof FkDropAreaAttributes]?: FkDropArea[K] } & { [K in keyof FkDropArea & keyof FkDropAreaAttributes as `attr:${K}`]?: FkDropAreaAttributes[K] } & { [K in keyof FkDropArea & keyof FkDropAreaAttributes as `prop:${K}`]?: FkDropArea[K] } & OneOf<"path", FkDropArea["path"], FkDropAreaAttributes["path"]>;
        "fk-empty-form": FkEmptyForm;
        "fk-file-input": Omit<FkFileInput, keyof FkFileInputAttributes> & { [K in keyof FkFileInput & keyof FkFileInputAttributes]?: FkFileInput[K] } & { [K in keyof FkFileInput & keyof FkFileInputAttributes as `attr:${K}`]?: FkFileInputAttributes[K] } & { [K in keyof FkFileInput & keyof FkFileInputAttributes as `prop:${K}`]?: FkFileInput[K] };
        "fk-form-builder": FkFormBuilder;
        "fk-form-render": Omit<FkFormRender, keyof FkFormRenderAttributes> & { [K in keyof FkFormRender & keyof FkFormRenderAttributes]?: FkFormRender[K] } & { [K in keyof FkFormRender & keyof FkFormRenderAttributes as `attr:${K}`]?: FkFormRenderAttributes[K] } & { [K in keyof FkFormRender & keyof FkFormRenderAttributes as `prop:${K}`]?: FkFormRender[K] };
        "fk-property-panel": Omit<FkPropertyPanel, keyof FkPropertyPanelAttributes> & { [K in keyof FkPropertyPanel & keyof FkPropertyPanelAttributes]?: FkPropertyPanel[K] } & { [K in keyof FkPropertyPanel & keyof FkPropertyPanelAttributes as `attr:${K}`]?: FkPropertyPanelAttributes[K] } & { [K in keyof FkPropertyPanel & keyof FkPropertyPanelAttributes as `prop:${K}`]?: FkPropertyPanel[K] };
        "fk-rules-editor": FkRulesEditor;
        "fk-select-input": Omit<FkSelectInput, keyof FkSelectInputAttributes> & { [K in keyof FkSelectInput & keyof FkSelectInputAttributes]?: FkSelectInput[K] } & { [K in keyof FkSelectInput & keyof FkSelectInputAttributes as `attr:${K}`]?: FkSelectInputAttributes[K] } & { [K in keyof FkSelectInput & keyof FkSelectInputAttributes as `prop:${K}`]?: FkSelectInput[K] };
        "fk-signature-input": Omit<FkSignatureInput, keyof FkSignatureInputAttributes> & { [K in keyof FkSignatureInput & keyof FkSignatureInputAttributes]?: FkSignatureInput[K] } & { [K in keyof FkSignatureInput & keyof FkSignatureInputAttributes as `attr:${K}`]?: FkSignatureInputAttributes[K] } & { [K in keyof FkSignatureInput & keyof FkSignatureInputAttributes as `prop:${K}`]?: FkSignatureInput[K] };
        "fk-stepper": Omit<FkStepper, keyof FkStepperAttributes> & { [K in keyof FkStepper & keyof FkStepperAttributes]?: FkStepper[K] } & { [K in keyof FkStepper & keyof FkStepperAttributes as `attr:${K}`]?: FkStepperAttributes[K] } & { [K in keyof FkStepper & keyof FkStepperAttributes as `prop:${K}`]?: FkStepper[K] };
        "fk-tabs": Omit<FkTabs, keyof FkTabsAttributes> & { [K in keyof FkTabs & keyof FkTabsAttributes]?: FkTabs[K] } & { [K in keyof FkTabs & keyof FkTabsAttributes as `attr:${K}`]?: FkTabsAttributes[K] } & { [K in keyof FkTabs & keyof FkTabsAttributes as `prop:${K}`]?: FkTabs[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fk-brick-actions": LocalJSX.IntrinsicElements["fk-brick-actions"] & JSXBase.HTMLAttributes<HTMLFkBrickActionsElement>;
            "fk-brick-list": LocalJSX.IntrinsicElements["fk-brick-list"] & JSXBase.HTMLAttributes<HTMLFkBrickListElement>;
            "fk-brick-mold-item": LocalJSX.IntrinsicElements["fk-brick-mold-item"] & JSXBase.HTMLAttributes<HTMLFkBrickMoldItemElement>;
            "fk-brick-not-found": LocalJSX.IntrinsicElements["fk-brick-not-found"] & JSXBase.HTMLAttributes<HTMLFkBrickNotFoundElement>;
            "fk-brick-render": LocalJSX.IntrinsicElements["fk-brick-render"] & JSXBase.HTMLAttributes<HTMLFkBrickRenderElement>;
            "fk-code-editor": LocalJSX.IntrinsicElements["fk-code-editor"] & JSXBase.HTMLAttributes<HTMLFkCodeEditorElement>;
            "fk-data-grid": LocalJSX.IntrinsicElements["fk-data-grid"] & JSXBase.HTMLAttributes<HTMLFkDataGridElement>;
            "fk-drop-area": LocalJSX.IntrinsicElements["fk-drop-area"] & JSXBase.HTMLAttributes<HTMLFkDropAreaElement>;
            "fk-empty-form": LocalJSX.IntrinsicElements["fk-empty-form"] & JSXBase.HTMLAttributes<HTMLFkEmptyFormElement>;
            "fk-file-input": LocalJSX.IntrinsicElements["fk-file-input"] & JSXBase.HTMLAttributes<HTMLFkFileInputElement>;
            "fk-form-builder": LocalJSX.IntrinsicElements["fk-form-builder"] & JSXBase.HTMLAttributes<HTMLFkFormBuilderElement>;
            "fk-form-render": LocalJSX.IntrinsicElements["fk-form-render"] & JSXBase.HTMLAttributes<HTMLFkFormRenderElement>;
            "fk-property-panel": LocalJSX.IntrinsicElements["fk-property-panel"] & JSXBase.HTMLAttributes<HTMLFkPropertyPanelElement>;
            "fk-rules-editor": LocalJSX.IntrinsicElements["fk-rules-editor"] & JSXBase.HTMLAttributes<HTMLFkRulesEditorElement>;
            "fk-select-input": LocalJSX.IntrinsicElements["fk-select-input"] & JSXBase.HTMLAttributes<HTMLFkSelectInputElement>;
            "fk-signature-input": LocalJSX.IntrinsicElements["fk-signature-input"] & JSXBase.HTMLAttributes<HTMLFkSignatureInputElement>;
            "fk-stepper": LocalJSX.IntrinsicElements["fk-stepper"] & JSXBase.HTMLAttributes<HTMLFkStepperElement>;
            "fk-tabs": LocalJSX.IntrinsicElements["fk-tabs"] & JSXBase.HTMLAttributes<HTMLFkTabsElement>;
        }
    }
}
