/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FkSample {
        /**
          * @default 'FormKrafter'
         */
        "name": string;
    }
}
declare global {
    interface HTMLFkSampleElement extends Components.FkSample, HTMLStencilElement {
    }
    var HTMLFkSampleElement: {
        prototype: HTMLFkSampleElement;
        new (): HTMLFkSampleElement;
    };
    interface HTMLElementTagNameMap {
        "fk-sample": HTMLFkSampleElement;
    }
}
declare namespace LocalJSX {
    interface FkSample {
        /**
          * @default 'FormKrafter'
         */
        "name"?: string;
    }

    interface FkSampleAttributes {
        "name": string;
    }

    interface IntrinsicElements {
        "fk-sample": Omit<FkSample, keyof FkSampleAttributes> & { [K in keyof FkSample & keyof FkSampleAttributes]?: FkSample[K] } & { [K in keyof FkSample & keyof FkSampleAttributes as `attr:${K}`]?: FkSampleAttributes[K] } & { [K in keyof FkSample & keyof FkSampleAttributes as `prop:${K}`]?: FkSample[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fk-sample": LocalJSX.IntrinsicElements["fk-sample"] & JSXBase.HTMLAttributes<HTMLFkSampleElement>;
        }
    }
}
