import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'

// Turns the JSONL the axe gate emits into the report the conformance dossier
// links to. Regenerating it is `bun run a11y:report`, so the dossier can never
// quote a number nobody can reproduce.

const [input = 'e2e/a11y-results.jsonl', output = 'docs/govstack/accessibility-report.md'] =
  process.argv.slice(2)

const scans = readFileSync(input, 'utf8')
  .split('\n')
  .filter(Boolean)
  .map((line) => JSON.parse(line))
  .sort((a, b) => a.scan.localeCompare(b.scan))

if (!scans.length) {
  console.error(`${input} holds no scan — run the audit first`)
  process.exit(1)
}

const violations = scans.reduce((n, s) => n + s.violations.length, 0)
const engine = scans[0].engine
const tags = scans[0].tags.join(', ')

const rows = scans
  .map(
    (s) =>
      `| ${s.scan} | ${s.passes} | ${s.incomplete} | ${
        s.violations.length === 0 ? '**0**' : `**${s.violations.length}**`
      } |`
  )
  .join('\n')

const detail = violations
  ? scans
      .filter((s) => s.violations.length)
      .map(
        (s) =>
          `### ${s.scan}\n\n` +
          s.violations
            .map(
              (v) =>
                `- \`${v.id}\` (${v.impact}) — ${v.help}\n` +
                v.nodes.map((n) => `  - \`${n}\``).join('\n')
            )
            .join('\n')
      )
      .join('\n\n')
  : 'No violation was reported on any scan.'

mkdirSync(output.replace(/\/[^/]+$/, ''), { recursive: true })
writeFileSync(
  output,
  `# Accessibility audit report

Generated by \`bun run a11y:report\` from a real run of the automated gate
([\`e2e/tests/a11y.spec.ts\`](../../e2e/tests/a11y.spec.ts)). Regenerate it
rather than editing it.

- **Engine** ${engine}
- **Rule set** ${tags}
- **Date** ${new Date().toISOString().slice(0, 10)}
- **Scans** ${scans.length}
- **Violations** ${violations}

## Results

| Scan | Rules passed | Needs review | Violations |
|---|---:|---:|---:|
${rows}

## Violations

${detail}

## What this does and does not establish

The gate fails the build on any violation, so the figure above is enforced on
every pull request rather than captured once. What automated rules cannot
establish is whether a form is *usable*: axe checks names, roles, contrast and
structure, not whether an error message is understandable or a drag-and-drop
interaction has a keyboard path a person would find. Those are covered by the
targeted tests listed in the conformance note, and by usability testing, which
has not been carried out yet.

The **needs review** column counts checks axe cannot decide alone; they are not
failures, and each one is a candidate for manual review.
`
)

console.log(`${output}: ${scans.length} scan(s), ${violations} violation(s)`)
