import { readFileSync, readdirSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

// Resolves the licence of every dependency the published packages actually
// ship, from the installed tree rather than from a registry lookup, so the
// report describes what a consumer receives.

const OUTPUT = process.argv[2] ?? 'docs/dpg/02-open-licence-report.md'

const packages = readdirSync('packages', { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name)

const licenceOf = (owner, name) => {
  for (const base of [`packages/${owner}/node_modules`, 'node_modules']) {
    const manifest = join(base, name, 'package.json')
    if (existsSync(manifest)) {
      const parsed = JSON.parse(readFileSync(manifest, 'utf8'))
      return { licence: parsed.license ?? 'unstated', version: parsed.version }
    }
  }
  return { licence: 'not installed', version: '—' }
}

const rows = []
for (const owner of packages) {
  const manifest = JSON.parse(readFileSync(`packages/${owner}/package.json`, 'utf8'))
  if (manifest.private) continue

  for (const [name, range] of Object.entries(manifest.dependencies ?? {})) {
    if (range.startsWith('workspace:')) continue
    const { licence, version } = licenceOf(owner, name)
    rows.push({ owner: manifest.name.replace('@streamline-pulse/', ''), name, version, licence })
  }
}

const own = packages
  .map((p) => JSON.parse(readFileSync(`packages/${p}/package.json`, 'utf8')))
  .filter((m) => !m.private)
  .map((m) => `| \`${m.name}\` | ${m.license ?? 'unstated'} |`)
  .join('\n')

const byLicence = rows.reduce((acc, r) => {
  acc[r.licence] = (acc[r.licence] ?? 0) + 1
  return acc
}, {})

const unexpected = Object.keys(byLicence).filter(
  (l) => !['MIT', 'Apache-2.0', 'ISC', 'BSD-2-Clause', 'BSD-3-Clause', '0BSD'].includes(l)
)

mkdirSync(OUTPUT.replace(/\/[^/]+$/, ''), { recursive: true })
writeFileSync(
  OUTPUT,
  `# 2 — Open licence

> DPG Standard indicator 2. Generated by \`bun run licence:report\` from the
> installed dependency tree — regenerate it rather than editing it.
> Date: ${new Date().toISOString().slice(0, 10)}

## The project

FormKrafter is released under the **MIT licence**
([\`LICENSE\`](../../LICENSE), Copyright 2026 Streamline Pulse), an
[OSI-approved](https://opensource.org/license/mit) licence. Every published
package declares it:

| Package | Licence |
|---|---|
${own}

## What the packages ship

Only runtime dependencies are listed: these are what a consumer installs.
Workspace dependencies are omitted — they are the packages above.

| Shipped by | Dependency | Version | Licence |
|---|---|---|---|
${rows
  .map((r) => `| \`${r.owner}\` | \`${r.name}\` | ${r.version} | ${r.licence} |`)
  .join('\n')}

Totals: ${Object.entries(byLicence)
    .map(([l, n]) => `**${n}** ${l}`)
    .join(', ')}.

${
  unexpected.length
    ? `> ⚠️ Licences outside the permissive set reviewed here: ${unexpected.join(', ')}. Review before release.`
    : `Every licence above is permissive and OSI-approved. None imposes a copyleft obligation on an application that installs FormKrafter, and none restricts commercial or governmental use.`
}

## Apache-2.0 in the tree

\`@atlaskit/pragmatic-drag-and-drop\` — the drag-and-drop primitives behind the
builder canvas — is Apache-2.0 rather than MIT. Apache-2.0 is OSI-approved and
permissive; it is compatible with redistribution inside an MIT-licensed project,
and it adds an express patent grant. What it asks in return is attribution:
distribute its licence text and any NOTICE with a distribution that includes it.

Two consequences worth stating plainly:

- It is only reachable through \`formkrafter-wc\`, so an application that uses
  \`formkrafter-core\` alone — a backend revalidating submissions, for instance —
  ships MIT only.
- Nothing here is a blocker for public-sector adoption. Apache-2.0 sits on the
  same approved lists as MIT for that purpose.

## No proprietary dependency

Nothing in the tree above is a paid, source-available or field-restricted
package, and FormKrafter requires no account, API key or hosted service to run.
See [4 — Platform independence](04-platform-independence.md).
`
)

console.log(
  `${OUTPUT}: ${rows.length} dependencies, ${Object.entries(byLicence)
    .map(([l, n]) => `${n} ${l}`)
    .join(', ')}`
)
