'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@streamline-pulse/formkrafter-wc/dist/components";
import { FkSample as FkSampleElement, defineCustomElement as defineFkSample } from "@streamline-pulse/formkrafter-wc/dist/components/fk-sample.js";

export type FkSampleEvents = NonNullable<unknown>;

export const FkSample: StencilReactComponent<FkSampleElement, FkSampleEvents, Components.FkSample> = /*@__PURE__*/ createComponent<FkSampleElement, FkSampleEvents, Components.FkSample>({
    tagName: 'fk-sample',
    elementClass: FkSampleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as FkSampleEvents,
    defineCustomElement: defineFkSample
});
