'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type BrickConfigsChangeDetail, type BrickDropDetail, type BrickPathDetail, type BrickRulesChangeDetail, type BrickStylesChangeDetail, type BrickValidationsChangeDetail, type DataChangeDetail, type FkBrickActionsCustomEvent, type FkBrickRenderCustomEvent, type FkCodeEditorCustomEvent, type FkDataGridCustomEvent, type FkDropAreaCustomEvent, type FkFileInputCustomEvent, type FkFormBuilderCustomEvent, type FkFormRenderCustomEvent, type FkPropertyPanelCustomEvent, type FkRulesEditorCustomEvent, type FkSelectInputCustomEvent, type FkSignatureInputCustomEvent, type FkStepperCustomEvent, type FkTabsCustomEvent, type SpecChangeDetail, type UploadedFile, type ValidityChangeDetail } from "@streamline-pulse/formkrafter-wc";
import type { Components } from "@streamline-pulse/formkrafter-wc/dist/components";
import { FkBrickActions as FkBrickActionsElement, defineCustomElement as defineFkBrickActions } from "@streamline-pulse/formkrafter-wc/dist/components/fk-brick-actions.js";
import { FkBrickList as FkBrickListElement, defineCustomElement as defineFkBrickList } from "@streamline-pulse/formkrafter-wc/dist/components/fk-brick-list.js";
import { FkBrickMoldItem as FkBrickMoldItemElement, defineCustomElement as defineFkBrickMoldItem } from "@streamline-pulse/formkrafter-wc/dist/components/fk-brick-mold-item.js";
import { FkBrickNotFound as FkBrickNotFoundElement, defineCustomElement as defineFkBrickNotFound } from "@streamline-pulse/formkrafter-wc/dist/components/fk-brick-not-found.js";
import { FkBrickRender as FkBrickRenderElement, defineCustomElement as defineFkBrickRender } from "@streamline-pulse/formkrafter-wc/dist/components/fk-brick-render.js";
import { FkCodeEditor as FkCodeEditorElement, defineCustomElement as defineFkCodeEditor } from "@streamline-pulse/formkrafter-wc/dist/components/fk-code-editor.js";
import { FkDataGrid as FkDataGridElement, defineCustomElement as defineFkDataGrid } from "@streamline-pulse/formkrafter-wc/dist/components/fk-data-grid.js";
import { FkDropArea as FkDropAreaElement, defineCustomElement as defineFkDropArea } from "@streamline-pulse/formkrafter-wc/dist/components/fk-drop-area.js";
import { FkEmptyForm as FkEmptyFormElement, defineCustomElement as defineFkEmptyForm } from "@streamline-pulse/formkrafter-wc/dist/components/fk-empty-form.js";
import { FkFileInput as FkFileInputElement, defineCustomElement as defineFkFileInput } from "@streamline-pulse/formkrafter-wc/dist/components/fk-file-input.js";
import { FkFormBuilder as FkFormBuilderElement, defineCustomElement as defineFkFormBuilder } from "@streamline-pulse/formkrafter-wc/dist/components/fk-form-builder.js";
import { FkFormRender as FkFormRenderElement, defineCustomElement as defineFkFormRender } from "@streamline-pulse/formkrafter-wc/dist/components/fk-form-render.js";
import { FkPropertyPanel as FkPropertyPanelElement, defineCustomElement as defineFkPropertyPanel } from "@streamline-pulse/formkrafter-wc/dist/components/fk-property-panel.js";
import { FkRulesEditor as FkRulesEditorElement, defineCustomElement as defineFkRulesEditor } from "@streamline-pulse/formkrafter-wc/dist/components/fk-rules-editor.js";
import { FkSelectInput as FkSelectInputElement, defineCustomElement as defineFkSelectInput } from "@streamline-pulse/formkrafter-wc/dist/components/fk-select-input.js";
import { FkSignatureInput as FkSignatureInputElement, defineCustomElement as defineFkSignatureInput } from "@streamline-pulse/formkrafter-wc/dist/components/fk-signature-input.js";
import { FkStepper as FkStepperElement, defineCustomElement as defineFkStepper } from "@streamline-pulse/formkrafter-wc/dist/components/fk-stepper.js";
import { FkTabs as FkTabsElement, defineCustomElement as defineFkTabs } from "@streamline-pulse/formkrafter-wc/dist/components/fk-tabs.js";

export type FkBrickActionsEvents = {
    onBrickRemove: EventName<FkBrickActionsCustomEvent<BrickPathDetail>>,
    onBrickDuplicate: EventName<FkBrickActionsCustomEvent<BrickPathDetail>>,
    onBrickDrop: EventName<FkBrickActionsCustomEvent<BrickDropDetail>>,
    onBrickSelect: EventName<FkBrickActionsCustomEvent<BrickPathDetail>>
};

export const FkBrickActions: StencilReactComponent<FkBrickActionsElement, FkBrickActionsEvents, Components.FkBrickActions, 'path'> = /*@__PURE__*/ createComponent<FkBrickActionsElement, FkBrickActionsEvents, Components.FkBrickActions, 'path'>({
    tagName: 'fk-brick-actions',
    elementClass: FkBrickActionsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onBrickRemove: 'brickRemove',
        onBrickDuplicate: 'brickDuplicate',
        onBrickDrop: 'brickDrop',
        onBrickSelect: 'brickSelect'
    } as FkBrickActionsEvents,
    defineCustomElement: defineFkBrickActions
});

export type FkBrickListEvents = NonNullable<unknown>;

export const FkBrickList: StencilReactComponent<FkBrickListElement, FkBrickListEvents, Components.FkBrickList> = /*@__PURE__*/ createComponent<FkBrickListElement, FkBrickListEvents, Components.FkBrickList>({
    tagName: 'fk-brick-list',
    elementClass: FkBrickListElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as FkBrickListEvents,
    defineCustomElement: defineFkBrickList
});

export type FkBrickMoldItemEvents = NonNullable<unknown>;

export const FkBrickMoldItem: StencilReactComponent<FkBrickMoldItemElement, FkBrickMoldItemEvents, Components.FkBrickMoldItem, 'brickMold'> = /*@__PURE__*/ createComponent<FkBrickMoldItemElement, FkBrickMoldItemEvents, Components.FkBrickMoldItem, 'brickMold'>({
    tagName: 'fk-brick-mold-item',
    elementClass: FkBrickMoldItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as FkBrickMoldItemEvents,
    defineCustomElement: defineFkBrickMoldItem
});

export type FkBrickNotFoundEvents = NonNullable<unknown>;

export const FkBrickNotFound: StencilReactComponent<FkBrickNotFoundElement, FkBrickNotFoundEvents, Components.FkBrickNotFound> = /*@__PURE__*/ createComponent<FkBrickNotFoundElement, FkBrickNotFoundEvents, Components.FkBrickNotFound>({
    tagName: 'fk-brick-not-found',
    elementClass: FkBrickNotFoundElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as FkBrickNotFoundEvents,
    defineCustomElement: defineFkBrickNotFound
});

export type FkBrickRenderEvents = {
    onBrickDataChange: EventName<FkBrickRenderCustomEvent<Record<string, unknown>>>,
    onBrickConfigsChange: EventName<FkBrickRenderCustomEvent<BrickConfigsChangeDetail>>,
    onBrickStylesChange: EventName<FkBrickRenderCustomEvent<BrickStylesChangeDetail>>,
    onBrickValidationsChange: EventName<FkBrickRenderCustomEvent<BrickValidationsChangeDetail>>,
    onBrickRulesChange: EventName<FkBrickRenderCustomEvent<BrickRulesChangeDetail>>,
    onBrickRemove: EventName<FkBrickRenderCustomEvent<BrickPathDetail>>,
    onBrickDuplicate: EventName<FkBrickRenderCustomEvent<BrickPathDetail>>
};

export const FkBrickRender: StencilReactComponent<FkBrickRenderElement, FkBrickRenderEvents, Components.FkBrickRender, 'brickSpec' | 'utils'> = /*@__PURE__*/ createComponent<FkBrickRenderElement, FkBrickRenderEvents, Components.FkBrickRender, 'brickSpec' | 'utils'>({
    tagName: 'fk-brick-render',
    elementClass: FkBrickRenderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onBrickDataChange: 'brickDataChange',
        onBrickConfigsChange: 'brickConfigsChange',
        onBrickStylesChange: 'brickStylesChange',
        onBrickValidationsChange: 'brickValidationsChange',
        onBrickRulesChange: 'brickRulesChange',
        onBrickRemove: 'brickRemove',
        onBrickDuplicate: 'brickDuplicate'
    } as FkBrickRenderEvents,
    defineCustomElement: defineFkBrickRender
});

export type FkCodeEditorEvents = { onCodeChange: EventName<FkCodeEditorCustomEvent<string>> };

export const FkCodeEditor: StencilReactComponent<FkCodeEditorElement, FkCodeEditorEvents, Components.FkCodeEditor> = /*@__PURE__*/ createComponent<FkCodeEditorElement, FkCodeEditorEvents, Components.FkCodeEditor>({
    tagName: 'fk-code-editor',
    elementClass: FkCodeEditorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCodeChange: 'codeChange' } as FkCodeEditorEvents,
    defineCustomElement: defineFkCodeEditor
});

export type FkDataGridEvents = { onGridValueChange: EventName<FkDataGridCustomEvent<Array<Record<string, unknown>> | undefined>> };

export const FkDataGrid: StencilReactComponent<FkDataGridElement, FkDataGridEvents, Components.FkDataGrid, 'spec' | 'utils'> = /*@__PURE__*/ createComponent<FkDataGridElement, FkDataGridEvents, Components.FkDataGrid, 'spec' | 'utils'>({
    tagName: 'fk-data-grid',
    elementClass: FkDataGridElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onGridValueChange: 'gridValueChange' } as FkDataGridEvents,
    defineCustomElement: defineFkDataGrid
});

export type FkDropAreaEvents = { onBrickDrop: EventName<FkDropAreaCustomEvent<BrickDropDetail>> };

export const FkDropArea: StencilReactComponent<FkDropAreaElement, FkDropAreaEvents, Components.FkDropArea, 'path'> = /*@__PURE__*/ createComponent<FkDropAreaElement, FkDropAreaEvents, Components.FkDropArea, 'path'>({
    tagName: 'fk-drop-area',
    elementClass: FkDropAreaElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onBrickDrop: 'brickDrop' } as FkDropAreaEvents,
    defineCustomElement: defineFkDropArea
});

export type FkEmptyFormEvents = NonNullable<unknown>;

export const FkEmptyForm: StencilReactComponent<FkEmptyFormElement, FkEmptyFormEvents, Components.FkEmptyForm> = /*@__PURE__*/ createComponent<FkEmptyFormElement, FkEmptyFormEvents, Components.FkEmptyForm>({
    tagName: 'fk-empty-form',
    elementClass: FkEmptyFormElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as FkEmptyFormEvents,
    defineCustomElement: defineFkEmptyForm
});

export type FkFileInputEvents = { onFileValueChange: EventName<FkFileInputCustomEvent<UploadedFile | UploadedFile[] | undefined>> };

export const FkFileInput: StencilReactComponent<FkFileInputElement, FkFileInputEvents, Components.FkFileInput> = /*@__PURE__*/ createComponent<FkFileInputElement, FkFileInputEvents, Components.FkFileInput>({
    tagName: 'fk-file-input',
    elementClass: FkFileInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onFileValueChange: 'fileValueChange' } as FkFileInputEvents,
    defineCustomElement: defineFkFileInput
});

export type FkFormBuilderEvents = { onSpecChange: EventName<FkFormBuilderCustomEvent<SpecChangeDetail>> };

export const FkFormBuilder: StencilReactComponent<FkFormBuilderElement, FkFormBuilderEvents, Components.FkFormBuilder> = /*@__PURE__*/ createComponent<FkFormBuilderElement, FkFormBuilderEvents, Components.FkFormBuilder>({
    tagName: 'fk-form-builder',
    elementClass: FkFormBuilderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSpecChange: 'specChange' } as FkFormBuilderEvents,
    defineCustomElement: defineFkFormBuilder
});

export type FkFormRenderEvents = {
    onFormDataChange: EventName<FkFormRenderCustomEvent<DataChangeDetail>>,
    onFormSubmit: EventName<FkFormRenderCustomEvent<DataChangeDetail>>,
    onValidityChange: EventName<FkFormRenderCustomEvent<ValidityChangeDetail>>
};

export const FkFormRender: StencilReactComponent<FkFormRenderElement, FkFormRenderEvents, Components.FkFormRender, 'spec'> = /*@__PURE__*/ createComponent<FkFormRenderElement, FkFormRenderEvents, Components.FkFormRender, 'spec'>({
    tagName: 'fk-form-render',
    elementClass: FkFormRenderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onFormDataChange: 'formDataChange',
        onFormSubmit: 'formSubmit',
        onValidityChange: 'validityChange'
    } as FkFormRenderEvents,
    defineCustomElement: defineFkFormRender
});

export type FkPropertyPanelEvents = {
    onBrickConfigsChange: EventName<FkPropertyPanelCustomEvent<BrickConfigsChangeDetail>>,
    onBrickValidationsChange: EventName<FkPropertyPanelCustomEvent<BrickValidationsChangeDetail>>,
    onBrickStylesChange: EventName<FkPropertyPanelCustomEvent<BrickStylesChangeDetail>>
};

export const FkPropertyPanel: StencilReactComponent<FkPropertyPanelElement, FkPropertyPanelEvents, Components.FkPropertyPanel, 'brick'> = /*@__PURE__*/ createComponent<FkPropertyPanelElement, FkPropertyPanelEvents, Components.FkPropertyPanel, 'brick'>({
    tagName: 'fk-property-panel',
    elementClass: FkPropertyPanelElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onBrickConfigsChange: 'brickConfigsChange',
        onBrickValidationsChange: 'brickValidationsChange',
        onBrickStylesChange: 'brickStylesChange'
    } as FkPropertyPanelEvents,
    defineCustomElement: defineFkPropertyPanel
});

export type FkRulesEditorEvents = { onBrickRulesChange: EventName<FkRulesEditorCustomEvent<BrickRulesChangeDetail>> };

export const FkRulesEditor: StencilReactComponent<FkRulesEditorElement, FkRulesEditorEvents, Components.FkRulesEditor, 'brick'> = /*@__PURE__*/ createComponent<FkRulesEditorElement, FkRulesEditorEvents, Components.FkRulesEditor, 'brick'>({
    tagName: 'fk-rules-editor',
    elementClass: FkRulesEditorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onBrickRulesChange: 'brickRulesChange' } as FkRulesEditorEvents,
    defineCustomElement: defineFkRulesEditor
});

export type FkSelectInputEvents = { onSelectValueChange: EventName<FkSelectInputCustomEvent<string | string[] | undefined>> };

export const FkSelectInput: StencilReactComponent<FkSelectInputElement, FkSelectInputEvents, Components.FkSelectInput> = /*@__PURE__*/ createComponent<FkSelectInputElement, FkSelectInputEvents, Components.FkSelectInput>({
    tagName: 'fk-select-input',
    elementClass: FkSelectInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSelectValueChange: 'selectValueChange' } as FkSelectInputEvents,
    defineCustomElement: defineFkSelectInput
});

export type FkSignatureInputEvents = { onSignatureChange: EventName<FkSignatureInputCustomEvent<string | undefined>> };

export const FkSignatureInput: StencilReactComponent<FkSignatureInputElement, FkSignatureInputEvents, Components.FkSignatureInput> = /*@__PURE__*/ createComponent<FkSignatureInputElement, FkSignatureInputEvents, Components.FkSignatureInput>({
    tagName: 'fk-signature-input',
    elementClass: FkSignatureInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSignatureChange: 'signatureChange' } as FkSignatureInputEvents,
    defineCustomElement: defineFkSignatureInput
});

export type FkStepperEvents = {
    onStepTouch: EventName<FkStepperCustomEvent<{ keys: string[] }>>,
    onStepperSubmit: EventName<FkStepperCustomEvent<void>>
};

export const FkStepper: StencilReactComponent<FkStepperElement, FkStepperEvents, Components.FkStepper> = /*@__PURE__*/ createComponent<FkStepperElement, FkStepperEvents, Components.FkStepper>({
    tagName: 'fk-stepper',
    elementClass: FkStepperElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onStepTouch: 'stepTouch',
        onStepperSubmit: 'stepperSubmit'
    } as FkStepperEvents,
    defineCustomElement: defineFkStepper
});

export type FkTabsEvents = { onStepTouch: EventName<FkTabsCustomEvent<{ keys: string[] }>> };

export const FkTabs: StencilReactComponent<FkTabsElement, FkTabsEvents, Components.FkTabs> = /*@__PURE__*/ createComponent<FkTabsElement, FkTabsEvents, Components.FkTabs>({
    tagName: 'fk-tabs',
    elementClass: FkTabsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onStepTouch: 'stepTouch' } as FkTabsEvents,
    defineCustomElement: defineFkTabs
});
